name: docs_pages_workflow


on:
  push:
    branches:
      - '*'   # trigger on any branch

permissions:
  contents: write

jobs:
  build_docs_job:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0   # fetch all history + branches

    - name: Install dependencies & build docs
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REF_NAME: ${{ github.ref_name }}
        GITHUB_REPOSITORY: ${{ github.repository }} # github.repository_name does not exists as a variable, repo name has to be parsed from here.
        GITHUB_ACTOR: ${{ github.actor }}
        OWNER: ${{ github.repository_owner }}
        CUSTOM_DOMAIN: ${{ secrets.CUSTOM_DOMAIN }} # CUSTOM DOMAIN WRITTEN IN GITHUB SECRETS
        LATEST_VERSION: ${{ secrets.LATEST_VERSION }} # The latest version of the documentation written in github secrets.

      run: |
        # Go to repo root
        cd ${{ github.workspace }}

        # Install system dependencies
        sudo apt-get update
        sudo apt-get install -y git rsync python3-venv python3-pip make

        # Create virtual environment
        python3 -m venv venv

        # Install Python packages using venv pip BEFORE activation
        ./venv/bin/pip install --upgrade pip
        ./venv/bin/pip install -r requirements.txt

        # Activate virtual environment
        source venv/bin/activate

        # Set current branch and all versions for version selector
        CURRENT_BRANCH="${GITHUB_REF_NAME}"
        ALL_VERSIONS=$(git for-each-ref --format='%(refname:short)' refs/remotes/origin/ \
          | sed 's|^origin/||' \
          | grep -viE '^(HEAD|gh-pages|main)$' \
          | grep -viE '^feature/')
        export CURRENT_BRANCH ALL_VERSIONS

        # Run the build script from docs directory
        ./docs/build_docs.sh
      shell: bash

